---
- name: Install Git and Git LFS
  ansible.builtin.apt:
    pkg: [git, git-lfs]

- name: Install Docker
  ansible.builtin.apt:
    pkg: [docker.io, docker-compose]

- name: Enable and start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Run Docker-in-Docker container
  community.docker.docker_container:
    name: dind_container
    image: docker:dind
    state: started
    restart_policy: always
    privileged: true
    published_ports:
      - 127.0.0.1:2376:2375
    command: dockerd -H tcp://0.0.0.0:2375 --tls=false

- name: Create group
  ansible.builtin.group:
    name: runner

- name: Create user
  ansible.builtin.user:
    name: runner
    home: /home/runner
    shell: /bin/bash
    comment: Forgejo Runner
    group: runner
    groups: [docker]
    password: "*"

# TODO: Verify GPG signature.
- name: Download binary
  ansible.builtin.get_url:
    url: https://code.forgejo.org/forgejo/runner/releases/download/v{{ forgejo_runner_version }}/forgejo-runner-{{ forgejo_runner_version }}-linux-amd64
    dest: /usr/local/bin/forgejo-runner
    mode: "0775"
    owner: root
    group: root

- name: Add service
  ansible.builtin.copy:
    src: forgejo-runner.service
    dest: /etc/systemd/system/forgejo-runner.service
    owner: root
    group: root
    mode: "0775"

- name: Enable and start service
  ansible.builtin.systemd_service:
    name: forgejo-runner
    state: started
    enabled: true
