---
- name: Install dependencies
  ansible.builtin.apt:
    pkg: [debian-keyring, debian-archive-keyring, apt-transport-https, curl]

- name: Copy PGP public key block
  ansible.builtin.copy:
    src: gpg.key
    dest: /tmp/gpg.key
    owner: root
    group: root
    mode: "0775"

- name: Write PGP/GPG key public ring
  ansible.builtin.command:
    gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /tmp/gpg.key

- name: Download sources list
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: "0775"
    owner: root
    group: root

- name: Install Caddy
  ansible.builtin.apt:
    pkg: caddy
    update_cache: true

- name: Enable and start service
  ansible.builtin.systemd_service:
    name: caddy
    state: started
    enabled: true
