---
forgejo_version: 15.0.0

forgejo_internal_token: "{{ lookup('scaleway.scaleway.scaleway_secret', 'forgejo-internal-token') | b64decode }}"
forgejo_jwt_secret: "{{ lookup('scaleway.scaleway.scaleway_secret', 'forgejo-jwt-secret') | b64decode }}"
forgejo_lfs_jwt_secret: "{{ lookup('scaleway.scaleway.scaleway_secret', 'forgejo-lfs-jwt-secret') | b64decode }}"
forgejo_secret_key: "{{ lookup('scaleway.scaleway.scaleway_secret', 'forgejo-secret-key') | b64decode }}"

signing_key: "{{ lookup('scaleway.scaleway.scaleway_secret', 'signing-key') | b64decode }}"
signing_key_id: "{{ lookup('scaleway.scaleway.scaleway_secret', 'signing-key-id') | b64decode }}"

smtp_host: "{{ lookup('scaleway.scaleway.scaleway_secret', 'smtp-host') | b64decode }}"
smtp_port: "{{ lookup('scaleway.scaleway.scaleway_secret', 'smtp-port') | b64decode }}"
smtp_user: "{{ lookup('scaleway.scaleway.scaleway_secret', 'smtp-user') | b64decode }}"
smtp_password: "{{ lookup('scaleway.scaleway.scaleway_secret', 'smtp-password') | b64decode }}"
